### ISSUE TITLE
Backup bugs

### ISSUE THREAD

**Issue by benkeen** [formtools/module-form_backup#3]
From: https://github.com/formtools/core/issues/120

> 1. Field Validation and Form Back Up - I have intermittently had issues with all my field validation settings being wiped and I have now pinpointed the problem to Form Backup. You can recreate this issue by doing the following:
> a) make a backup copy of a form that has validation set on some of its fields
> b) delete the copied form (orphan clean-up reveals that the validation entries that were associated with this deleted from have not been removed from ft_field_validation table
> c) delete these orphaned records through Orphan Clean-up
> d) check the ft_field_validation table in your database - the orphaned records have been deleted but also, all validation entries associated with the ORIGINAL form (that you copied) have also been deleted
> e) validation entries associated with multiple non-related OTHER FORMS also get deleted!
> 
> A similar problem occurs when you delete any FIELD from a form that had a validation associated with it - the record of the validation in ft_field_validation does not get removed after you delete the form and then if you run Orphan Clean-up, it can delete random validation records for other non-related forms.

**Comment by tomheaps** [comment]
No need to apologize @benkeen - these sorts of issues are to be expected in alpha release.
I'm not convinced that the whole problem is due to Form Backup (which is why I originally posted in core) because it also occurs when you delete a single field with validation settings from any form - the validation settings associated with that field are not removed from ft_field_validation table and when you run Orphan Clean-up to remove these validation records it can delete multiple other validation settings from other forms - not just the field that you had deleted.

One thought I had is that the script might be deleting records from ft_field_validation according to `rule_id` rather than by `field_id`??

**Comment by benkeen** [comment]
Yes, that thought struck me too. Possibly there's a bug in the System Check module that's gone unnoticed until now. I have a couple of chores to run after work today & tomorrow, but I'll try to find time to get to the bottom of this soon. Thanks!

**Comment by tomheaps** [comment]
So @benkeen, after further testing and observation of what is happening in my database, I can confirm that my suspicions were correct - this is nothing to do with Form Backup but is an error in the core script and the Orphan clean-up process. To crystallize these issues in the hope that you can fix them:

**Issue 1.**

When deleting a field/s from a form OR when deleting an entire form, any validation settings associated with the deleted field/s or with the fields that were in the deleted form are NOT being deleted from the `ft_field_validation` table in the database - these orphaned validation records in `ft_field_validation` are highlighted if you run Orphan Clean-up after deleting a field/s or an entire form.

Expected behaviour - deletion of a field/s from a form OR deletion of an entire form should result in deletion of any associated validation records from `ft_field_validation`

-------------------------------------------------------------------------------------------------------------------

**Issue 2.** 

If you then use Orphan clean-up to delete the orphaned records in `ft_field_validation` it deletes ALL records from `ft_field_validation` where the `rule_id` is the same as the `rule_id` of the orphaned validation records e.g. if you have deleted a textbox field with a validation attached (`rule_id` = 1), Orphan clean-up will delete ALL validation rules associated with every textbox field (`rule_id` = 1) across your entire database. Obviously, if you are deleting an entire form that contains multiple different field types, each with a validation rule attached (i.e. multiple `rule_id`s), the chances are that when you next run Orphan clean-up, it will remove virtually all validation rules in your database.

Expected behaviour - Orphan clean-up should only delete validation records that were associated with the field/s that were deleted i.e. delete by `field_id` in the `ft_field_validation` table rather than by `rule_id`

-------------------------------------------------------------------------------------------------------------------

Fixing issue 1. will largely negate issue 2. but obviously you will want to ensure that if a validation record/s does get orphaned, running Orphan clean-up does not result in wholesale destruction of your `ft_field_validation` table!

Hope this helps and don't worry if you can't sort it immediately, I will just avoid setting any more validation rules until it is fixed!

**Comment by benkeen** [comment]
Hey @tomheaps - check out the latest System Check module:
https://github.com/formtools/module-system_check/releases/tag/2.1.3

That fixes the problem where it was accidentally removing valid field validation rules in the orphan cleanup step. However, there's still a bug with the Form Tools Core where deleting a form doesn't delete the field validation rules as well, ironically leaving some orphaned records. :) I'll take a look at that tonight.

**Comment by benkeen** [comment]
Yup, you totally nailed it in your last remarks. It's now fixed in the core. I want to do a little more testing, but it should be good - I'll release a new version tonight. Thanks!

I'll close this now since it wasn't the Form Backup after all... :)
